### ISSUE TITLE
Error with Markdown 3.x

### ISSUE THREAD

**Issue by SteveClement** [ryneeverett/python-markdown-comments#3]
Trying to enable the plugin on Markdown==3.0.1 (via mkdocs) yields the following:

```
$ mkdocs serve
INFO    -  Building documentation... 
ERROR   -  Config value: 'markdown_extensions'. Error: configs 

Aborted with 1 Configuration Errors!
```

Perhaps an issue here: https://github.com/ryneeverett/python-markdown-comments/blob/bd7a90fd8eed6fa49ca12b12b5b35580b0058dd3/mkdcomments.py#L64

**Comment by ryneeverett** [comment]
Resolved by #5.
